# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainLogin(object):
    def setupUi(self, MainLogin):
        MainLogin.setObjectName("MainLogin")
        MainLogin.resize(385, 529)
        MainLogin.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=MainLogin)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 10, 361, 461))
        self.stackedWidget.setStyleSheet("background-color:rgb(208, 208, 208)")
        self.stackedWidget.setObjectName("stackedWidget")
        self.Login = QtWidgets.QWidget()
        self.Login.setObjectName("Login")
        self.groupBox = QtWidgets.QGroupBox(parent=self.Login)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 321, 441))
        self.groupBox.setStyleSheet("")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.txt_userName = QtWidgets.QLineEdit(parent=self.groupBox)
        self.txt_userName.setGeometry(QtCore.QRect(130, 60, 141, 21))
        self.txt_userName.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_userName.setObjectName("txt_userName")
        self.txt_passWord = QtWidgets.QLineEdit(parent=self.groupBox)
        self.txt_passWord.setGeometry(QtCore.QRect(130, 110, 141, 21))
        self.txt_passWord.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_passWord.setObjectName("txt_passWord")
        self.btn_login = QtWidgets.QPushButton(parent=self.groupBox)
        self.btn_login.setGeometry(QtCore.QRect(100, 180, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_login.setFont(font)
        self.btn_login.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"color: rgb(255, 255, 255);")
        self.btn_login.setObjectName("btn_login")
        self.stackedWidget.addWidget(self.Login)
        MainLogin.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainLogin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 385, 21))
        self.menubar.setObjectName("menubar")
        MainLogin.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainLogin)
        self.statusbar.setObjectName("statusbar")
        MainLogin.setStatusBar(self.statusbar)

        self.retranslateUi(MainLogin)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainLogin)

    def retranslateUi(self, MainLogin):
        _translate = QtCore.QCoreApplication.translate
        MainLogin.setWindowTitle(_translate("MainLogin", "MainWindow"))
        self.label_2.setText(_translate("MainLogin", "Username"))
        self.label_3.setText(_translate("MainLogin", "Password"))
        self.btn_login.setText(_translate("MainLogin", "Đăng nhập"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainLogin = QtWidgets.QMainWindow()
    ui = Ui_MainLogin()
    ui.setupUi(MainLogin)
    MainLogin.show()
    sys.exit(app.exec())
